# Site wide configuration

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: drafts
    values:
      layout: post

title:            Continuity Engineering
locale:           en_US
#url:              http://engineering.continuity.net # having URL causes weird https related issues
description:      Helping Save Community Financial Institutions


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true
  input: GFM
  syntax_highlighter: pygments

# Site owner
owner:
  name: Continuity
  avatar: nu.png
  bio: Helping Save Community Financial Institutions
  email:
  disqus-shortname:
  twitter: ContinuityCTRL
  facebook: #username
  google:
    plus: #username
    analytics: UA-31337942-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ContinuityControl
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: company/continuity-control
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
